/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.rendering.block;

import java.util.List;
import java.util.Map;

import org.xwiki.rendering.listener.Listener;

/**
 * A special block that Macro Blocks generate when they are executed so that it's possible to reconstruct the initial
 * syntax even after Macros have been executed. For example this is important in a WYSWIYG editor where you want to show
 * the Macro's rendered result and also let users modify the macro content.
 *
 * @version $Id$
 * @since 1.5M2
 */
public class MacroMarkerBlock extends AbstractMacroBlock
{
    /**
     * Create a MacroMarkerBlock that represents a macro marker used to reconstruct the original macro syntax (for editing).
     *
     * @param id the macro identifier
     * @param parameters the macro parameters mapped by name
     * @param childBlocks the child blocks produced by the macro
     * @param isInline true if the macro is located inside inline content (for example, within a paragraph)
     */
    public MacroMarkerBlock(String id, Map<String, String> parameters, List<Block> childBlocks, boolean isInline)
    {
        this(id, parameters, null, childBlocks, isInline);
    }

    /**
     * Create a MacroMarkerBlock that records the macro identifier, its parameters, optional content, produced child
     * blocks and whether the macro appears inline.
     *
     * @param id the macro identifier
     * @param parameters a map of macro parameter names to their values
     * @param content the macro content, or {@code null} if the macro has no content
     * @param childBlocks the blocks generated by the macro's execution
     * @param inline {@code true} if the macro is located inside inline content (for example inside a paragraph)
     */
    public MacroMarkerBlock(String id, Map<String, String> parameters, String content, List<Block> childBlocks,
        boolean inline)
    {
        super(childBlocks, parameters, id, content, inline);
    }

    /**
     * Provide the macro identifier for backwards compatibility with older APIs.
     *
     * @return the macro identifier
     * @deprecated since 2.4M1; use {@link #getId()} instead.
     */
    @Deprecated
    public String getName()
    {
        return getId();
    }

    /**
     * Notifies the listener that a macro marker begins using this block's id, parameters, content, and inline flag.
     *
     * @param listener the listener to receive the begin macro marker event
     */
    @Override
    public void before(Listener listener)
    {
        listener.beginMacroMarker(getId(), getParameters(), getContent(), isInline());
    }

    /**
     * Notify the listener that this macro marker has ended.
     *
     * @param listener the listener to notify with an endMacroMarker event carrying this block's id, parameters, content, and inline flag
     */
    @Override
    public void after(Listener listener)
    {
        listener.endMacroMarker(getId(), getParameters(), getContent(), isInline());
    }
}